/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaSqliteRouteImport } from './routes/wa-sqlite'
import { Route as LocalstorageRouteImport } from './routes/localstorage'
import { Route as IndexeddbRouteImport } from './routes/indexeddb'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTodosRouteImport } from './routes/api/todos'
import { Route as ApiTodosTodoIdRouteImport } from './routes/api/todos.$todoId'

const WaSqliteRoute = WaSqliteRouteImport.update({
  id: '/wa-sqlite',
  path: '/wa-sqlite',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalstorageRoute = LocalstorageRouteImport.update({
  id: '/localstorage',
  path: '/localstorage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexeddbRoute = IndexeddbRouteImport.update({
  id: '/indexeddb',
  path: '/indexeddb',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosRoute = ApiTodosRouteImport.update({
  id: '/api/todos',
  path: '/api/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosTodoIdRoute = ApiTodosTodoIdRouteImport.update({
  id: '/$todoId',
  path: '/$todoId',
  getParentRoute: () => ApiTodosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/indexeddb': typeof IndexeddbRoute
  '/localstorage': typeof LocalstorageRoute
  '/wa-sqlite': typeof WaSqliteRoute
  '/api/todos': typeof ApiTodosRouteWithChildren
  '/api/todos/$todoId': typeof ApiTodosTodoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/indexeddb': typeof IndexeddbRoute
  '/localstorage': typeof LocalstorageRoute
  '/wa-sqlite': typeof WaSqliteRoute
  '/api/todos': typeof ApiTodosRouteWithChildren
  '/api/todos/$todoId': typeof ApiTodosTodoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/indexeddb': typeof IndexeddbRoute
  '/localstorage': typeof LocalstorageRoute
  '/wa-sqlite': typeof WaSqliteRoute
  '/api/todos': typeof ApiTodosRouteWithChildren
  '/api/todos/$todoId': typeof ApiTodosTodoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/indexeddb'
    | '/localstorage'
    | '/wa-sqlite'
    | '/api/todos'
    | '/api/todos/$todoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/indexeddb'
    | '/localstorage'
    | '/wa-sqlite'
    | '/api/todos'
    | '/api/todos/$todoId'
  id:
    | '__root__'
    | '/'
    | '/indexeddb'
    | '/localstorage'
    | '/wa-sqlite'
    | '/api/todos'
    | '/api/todos/$todoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndexeddbRoute: typeof IndexeddbRoute
  LocalstorageRoute: typeof LocalstorageRoute
  WaSqliteRoute: typeof WaSqliteRoute
  ApiTodosRoute: typeof ApiTodosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wa-sqlite': {
      id: '/wa-sqlite'
      path: '/wa-sqlite'
      fullPath: '/wa-sqlite'
      preLoaderRoute: typeof WaSqliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localstorage': {
      id: '/localstorage'
      path: '/localstorage'
      fullPath: '/localstorage'
      preLoaderRoute: typeof LocalstorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indexeddb': {
      id: '/indexeddb'
      path: '/indexeddb'
      fullPath: '/indexeddb'
      preLoaderRoute: typeof IndexeddbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos': {
      id: '/api/todos'
      path: '/api/todos'
      fullPath: '/api/todos'
      preLoaderRoute: typeof ApiTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos/$todoId': {
      id: '/api/todos/$todoId'
      path: '/$todoId'
      fullPath: '/api/todos/$todoId'
      preLoaderRoute: typeof ApiTodosTodoIdRouteImport
      parentRoute: typeof ApiTodosRoute
    }
  }
}

interface ApiTodosRouteChildren {
  ApiTodosTodoIdRoute: typeof ApiTodosTodoIdRoute
}

const ApiTodosRouteChildren: ApiTodosRouteChildren = {
  ApiTodosTodoIdRoute: ApiTodosTodoIdRoute,
}

const ApiTodosRouteWithChildren = ApiTodosRoute._addFileChildren(
  ApiTodosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndexeddbRoute: IndexeddbRoute,
  LocalstorageRoute: LocalstorageRoute,
  WaSqliteRoute: WaSqliteRoute,
  ApiTodosRoute: ApiTodosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
